"use client";

import { useEffect, useState } from "react";
import { supabase } from "@/lib/supabase";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export default function ReportsDashboard() {
  const [revenue, setRevenue] = useState(0);
  const [expenses, setExpenses] = useState(0);
  const [production, setProduction] = useState(0);
  const [crates, setCrates] = useState(0);
  const [period, setPeriod] = useState("This Month");

  useEffect(() => {
    loadReports();
  }, [period]);

  async function loadReports() {
    let startDate: string | null = null;

    const today = new Date();

    switch (period) {
      case "Today":
        startDate = today.toISOString().split("T")[0];
        break;

      case "This Week": {
        const firstDay = new Date(today);
        firstDay.setDate(today.getDate() - today.getDay());
        startDate = firstDay.toISOString();
        break;
      }

      case "This Month": {
        const firstDay = new Date(
          today.getFullYear(),
          today.getMonth(),
          1
        );
        startDate = firstDay.toISOString();
        break;
      }

      case "This Year": {
        const firstDay = new Date(today.getFullYear(), 0, 1);
        startDate = firstDay.toISOString();
        break;
      }

      default:
        startDate = null;
    }

    const { data: sales } = await supabase
      .from("egg_sales")
      .select("total_amount");

    const { data: expense } = await supabase
      .from("expenses")
      .select("amount");

    const { data: productionData } = await supabase
      .from("egg_production")
      .select("birds,crates")
      .order("created_at", { ascending: false })
      .limit(1);

    const totalRevenue =
      sales?.reduce(
        (sum, sale) => sum + Number(sale.total_amount ?? 0),
        0
      ) || 0;

    const totalExpenses =
      expense?.reduce(
        (sum, item) => sum + Number(item.amount ?? 0),
        0
      ) || 0;

    if (productionData && productionData.length > 0) {
      const latest = productionData[0];

      setCrates(latest.crates);

      setProduction(
        ((latest.crates * 30) / latest.birds) * 100
      );
    }

    setRevenue(totalRevenue);
    setExpenses(totalExpenses);
  }

  const profit = revenue - expenses;

  function exportPDF() {
    const doc = new jsPDF();

    doc.setFontSize(22);
    doc.setTextColor(0, 128, 0);
    doc.text("Mide Farm ERP", 14, 18);

    doc.setFontSize(13);
    doc.setTextColor(80);
    doc.text("Executive Business Report", 14, 28);

    doc.text(
      `Generated: ${new Date().toLocaleString()}`,
      14,
      36
    );

    autoTable(doc, {
      startY: 45,
      head: [["Metric", "Value"]],
      body: [
        ["Revenue", `₦${revenue.toLocaleString()}`],
        ["Expenses", `₦${expenses.toLocaleString()}`],
        ["Net Profit", `₦${profit.toLocaleString()}`],
        ["Production", `${production.toFixed(1)}%`],
        ["Today's Crates", `${crates}`],
      ],
      headStyles: {
        fillColor: [22, 163, 74],
      },
      styles: {
        fontSize: 11,
      },
    });

    doc.setFontSize(11);

    doc.text(
      "Generated by Mide Farm ERP",
      14,
      (doc as any).lastAutoTable.finalY + 20
    );

    doc.save("Mide_Farm_Executive_Report.pdf");
  }

  return (
    <>
      <div className="mb-8 flex flex-col gap-6 lg:flex-row lg:items-center lg:justify-between">

        <div>
          <h1 className="text-3xl font-bold sm:text-4xl">
            📊 Executive Reports
          </h1>

          <p className="mt-2 text-sm sm:text-base text-slate-400">
            Live business performance summary.
          </p>
        </div>

        <div className="flex flex-col gap-3 sm:flex-row">

          <select
            value={period}
            onChange={(e) => setPeriod(e.target.value)}
            className="rounded-xl border border-slate-700 bg-slate-800 px-4 py-3 text-white focus:border-green-500 focus:outline-none"
          >
            <option>Today</option>
            <option>This Week</option>
            <option>This Month</option>
            <option>This Year</option>
            <option>All Time</option>
          </select>

          <button
            onClick={exportPDF}
            className="rounded-xl bg-green-600 px-6 py-3 font-semibold text-white transition hover:scale-[1.02] hover:bg-green-500"
          >
            📄 Export PDF
          </button>

        </div>

      </div>

      <div className="grid grid-cols-1 gap-5 sm:grid-cols-2 xl:grid-cols-4">

        <ReportCard
          title="Revenue"
          value={`₦${revenue.toLocaleString()}`}
          color="text-green-400"
        />

        <ReportCard
          title="Expenses"
          value={`₦${expenses.toLocaleString()}`}
          color="text-red-400"
        />

        <ReportCard
          title="Profit"
          value={`₦${profit.toLocaleString()}`}
          color={
            profit >= 0
              ? "text-green-400"
              : "text-red-400"
          }
        />

        <ReportCard
          title="Production"
          value={`${production.toFixed(1)}%`}
          color="text-blue-400"
        />

      </div>

      <div className="mt-8 rounded-3xl border border-slate-800 bg-slate-900 p-4 sm:p-6 lg:p-8 shadow-xl">

        <h2 className="text-xl font-bold sm:text-2xl">
          Business Summary
        </h2>

        <div className="mt-6 sm:mt-8 space-y-4">

          <SummaryRow
            label="Total Revenue"
            value={`₦${revenue.toLocaleString()}`}
          />

          <SummaryRow
            label="Total Expenses"
            value={`₦${expenses.toLocaleString()}`}
          />

          <SummaryRow
            label="Net Profit"
            value={`₦${profit.toLocaleString()}`}
          />

          <SummaryRow
            label="Today's Production"
            value={`${production.toFixed(1)}%`}
          />

          <SummaryRow
            label="Today's Crates"
            value={`${crates} Crates`}
          />

        </div>

      </div>
    </>
  );
}

function ReportCard({
  title,
  value,
  color,
}: {
  title: string;
  value: string;
  color: string;
}) {
  return (
    <div className="rounded-3xl border border-slate-800 bg-slate-900 p-4 sm:p-6 shadow-xl">

      <p className="text-sm text-slate-400">
        {title}
      </p>

      <h2 className={`mt-4 break-words text-2xl sm:text-4xl font-bold ${color}`}>
        {value}
      </h2>

    </div>
  );
}

function SummaryRow({
  label,
  value,
}: {
  label: string;
  value: string;
}) {
  return (
    <div className="flex flex-col gap-2 border-b border-slate-800 pb-4 sm:flex-row sm:items-center sm:justify-between">

      <span className="text-slate-400">
        {label}
      </span>

      <span className="font-semibold break-words">
        {value}
      </span>

    </div>
  );
}