create table if not exists public.egg_adjustments (
  id bigint generated by default as identity primary key,
  date date not null,
  crates integer not null default 0 check (crates >= 0),
  pieces integer not null default 0 check (pieces >= 0 and pieces < 30),
  reason text not null,
  notes text,
  created_at timestamptz not null default now(),
  check (crates > 0 or pieces > 0)
);

create index if not exists egg_adjustments_date_idx
  on public.egg_adjustments (date desc);
