create table if not exists public.medication_records (
  id bigint generated by default as identity primary key,
  date date not null,
  medication_name text not null,
  purpose text not null,
  dosage text,
  quantity text,
  cost numeric not null default 0 check (cost >= 0),
  notes text,
  created_at timestamptz not null default now()
);

create index if not exists medication_records_date_idx
  on public.medication_records (date desc);
